export const MODULE_LABELS: Record<string, string> = {
  accounts: 'Cuentas',
  contacts: 'Contactos',
  relations: 'Relaciones',
  'crm-entities': 'CRM',
  tags: 'Etiquetas',
  search: 'Búsqueda',
  dashboard: 'Dashboard',
  tasks: 'Tareas',
  interactions: 'Interacciones',
  activities: 'Actividades',
  segments: 'Segmentos',
  teams: 'Equipos',
  automation: 'Automatización',
  documents: 'Documentos',
  inventory: 'Inventario',
  quotations: 'Cotizaciones',
  products: 'Productos',
  'price-books': 'Listas de precios',
  commissions: 'Comisiones',
  opportunities: 'Oportunidades',
  finance: 'Finanzas',
  reports: 'Reportes',
  'custom-fields': 'Campos personalizados',
  settings: 'Configuración',
  logs: 'Logs',
  metrics: 'Métricas',
  plans: 'Planes',
  admin: 'Admin',
  users: 'Usuarios',
  expenses: 'Gastos',
  purchases: 'Compras',
  'competitive-intelligence': 'Inteligencia competitiva',
  partners: 'Socios',
  projects: 'Proyectos',
};
