// ─────────────────────────────────────────────────────────────────────────────
// Icon — Componente centralizado de iconos
// ─────────────────────────────────────────────────────────────────────────────

import {
  Activity,
  ALargeSmall,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  BarChart2,
  BarChart3,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  // ── Admin ──────────────────────────────────────────────────────────────
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  ClipboardList,
  Clock,
  // ── UI / Feedback ───────────────────────────────────────────────────────────
  Cloud,
  Contrast,
  Copy,
  CreditCard,
  Crown,
  DatabaseZap,
  DollarSign,
  Download,
  Edit,
  Edit2,
  ExternalLink,
  // ── Auth / Seguridad ────────────────────────────────────────────────────────
  Eye,
  EyeOff,
  File,
  FileDown,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileType,
  Filter,
  Flag,
  Flame,
  // ── Proyectos ───────────────────────────────────────────────────────────
  FolderKanban,
  FolderOpen,
  FolderX,
  Footprints,
  Globe,
  GraduationCap,
  // ── Partners / PRM ──────────────────────────────────────────────────────
  Handshake,
  HardDrive,
  Headphones,
  History,
  Info,
  KanbanSquare,
  Landmark,
  Languages,
  Layers,
  // ── Navegación ──────────────────────────────────────────────────────────────
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Lightbulb,
  Link2,
  Linkedin,
  List,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  type LucideIcon,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  // ── Negocio / Módulos ───────────────────────────────────────────────────────
  Package,
  PackageOpen,
  PackagePlus,
  Paintbrush,
  PanelBottom,
  PanelLeft,
  PauseCircle,
  Pencil,
  Phone,
  PhoneCall,
  PieChart,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  Power,
  Presentation,
  Receipt,
  RefreshCcw,
  RefreshCw,
  Save,
  // ── Acciones ──────────────────────────────────────────────────────────────
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShieldOff,
  Shirt,
  ShoppingCart,
  Sliders,
  SlidersHorizontal,
  SplitSquareVertical,
  SquarePen,
  StickyNote,
  Store,
  StretchHorizontal,
  Sun,
  SunSnow,
  // Inteligencia Competitiva
  Swords,
  Tag,
  Tags,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Unlink,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserPlus,
  Users,
  UsersRound,
  UserX,
  Warehouse,
  X,
  XCircle,
  // Automatización
  Zap,
} from 'lucide-react';

// ─────────────────────────────────────────────────────────────────────────────
// Registro de iconos (implementación interna — no exportado)
// Para agregar un nuevo ícono: importarlo arriba y añadirlo aquí.
// ─────────────────────────────────────────────────────────────────────────────
const icons = {
  // Navegación
  LayoutDashboard,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  Menu,
  X,
  SlidersHorizontal,
  Sun,
  Moon,
  Monitor,
  Check,
  PanelLeft,
  PanelBottom,
  StretchHorizontal,
  ALargeSmall,
  Circle,
  Contrast,
  Box,
  Layers,
  LayoutGrid,
  LayoutTemplate,
  ExternalLink,

  // Auth
  Eye,
  EyeOff,
  Mail,
  Lock,
  ShieldCheck,
  ShieldOff,
  User,

  // Negocio
  Package,
  List,
  Tag,
  Tags,
  Warehouse,
  BarChart2,
  BarChart3,
  ArrowLeftRight,
  LogIn,
  LogOut,
  RefreshCcw,
  RefreshCw,
  CalendarDays,
  Calendar,
  Users,
  UsersRound,
  ShoppingCart,
  DollarSign,
  FileText,
  FileDown,
  TrendingUp,
  TrendingDown,
  Settings,
  AlertTriangle,
  AlertOctagon,
  AlertCircle,
  Shirt,
  Footprints,
  SunSnow,
  PieChart,
  PackageOpen,
  Briefcase,
  Receipt,
  Landmark,
  Languages,
  Globe,
  Phone,
  PhoneCall,
  MapPin,
  Link2,
  Unlink,
  Bell,
  HardDrive,
  DatabaseZap,
  Filter,

  // Acciones
  Search,
  Plus,
  PlusCircle,
  Pencil,
  Edit,
  Edit2,
  SquarePen,
  Trash2,
  Download,
  Upload,
  UploadCloud,
  ArrowRight,
  ArrowLeft,
  Store,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  XCircle,
  UserPlus,
  UserX,
  UserCheck,
  Clock,
  Save,
  Send,
  Copy,
  Play,
  PlayCircle,
  Power,
  SplitSquareVertical,

  Paintbrush,

  // UI / Feedback
  Cloud,
  Info,
  Loader2,
  Minus,
  PackagePlus,
  MoreHorizontal,
  MoreVertical,
  MessageSquare,
  StickyNote,
  Flame,
  Trophy,
  Crown,
  Lightbulb,
  Calculator,
  File,
  FileSpreadsheet,
  FileType,
  Sliders,

  // Admin
  Building2,
  CreditCard,
  Activity,
  Shield,
  Headphones,

  // Proyectos
  FolderKanban,
  History,
  KanbanSquare,
  PauseCircle,
  FolderX,
  Flag,

  // Partners / PRM
  Handshake,
  ClipboardList,
  FolderOpen,
  GraduationCap,
  BookOpen,
  FileSignature,
  Presentation,

  // Inteligencia Competitiva
  Swords,
  Target,

  // Automatización
  Zap,
  Linkedin,
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// Tipos
// ─────────────────────────────────────────────────────────────────────────────
export type IconName = keyof typeof icons;

export type { LucideIcon };

// ─────────────────────────────────────────────────────────────────────────────
// Componente <Icon />
//
// Uso:
//   <Icon name="Mail" size={16} />
//   <Icon name="ChevronRight" className="text-primary" />
// ─────────────────────────────────────────────────────────────────────────────
interface IconProps {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
}

export function Icon({ name, size = 16, strokeWidth, className }: IconProps) {
  const LucideIconComponent = icons[name] ?? icons.Circle;
  return <LucideIconComponent size={size} strokeWidth={strokeWidth} className={className} />;
}
